version: "3.1"

services:

  mysql:
    image: mysql:5.7
    container_name: whatazoo-db-mysql
    working_dir: /application
    volumes:
      - .:/application
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    entrypoint:
      sh -c "
      echo 'CREATE DATABASE IF NOT EXISTS ${DB_DATABASE}; CREATE DATABASE IF NOT EXISTS ${DB_TESTING};' > /docker-entrypoint-initdb.d/init.sql;
      /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      "
    ports:
      - "3306:3306"

  webserver:
    image: nginx:alpine
    container_name: whatazoo-db-webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "777:80"

  php-fpm:
    build:
      context: ./.docker/php-fpm
      args:
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
        - XDEBUG_HOST=${XDEBUG_HOST}
        - XDEBUG_PORT=${XDEBUG_PORT}
        - XDEBUG_AUTOSTART=${XDEBUG_AUTOSTART}
    container_name: whatazoo-db-php-fpm
    working_dir: /application
    volumes:
      - .:/application
      - ./.docker/conf/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini